export const DRAG_DATA_TRANSFER = "DRAGGED_NODE";
export const DRAG_CLASS = "HESABA_DRAG_HANDLER";
export const HESABA_TABLE_HEADER_CLASS = "HESABA_TABLE_HEADER_CLASS";

export const HESABA_TABLE_ROW_CLASS = "HESABA_TABLE_ROW_CLASS";

export const HESABA_DATA_FIELD = "HESABA_DATA_FIELD";

export const DATA_FIELD = "data-field"

